### PR TITLE
Don't wait on deletion

### LINKED ISSUE #213: [bug] futures negatively impacted by garbage collection
In the process of getting `pympipool` to play well with `pyiron_workflow`, I have been playing around a bunch with callbacks and using executors sans the `with` context. (See #187 and #210 for discussion.)

After repeated narrowing of my MWE, I ended up with this:

```python
from pympipool.mpi.executor import PyMPIExecutor as Executor

mutable = []

def slow_callable():
    from time import sleep
    sleep(1)
    return True

def callback(future):
    mutable.append("Called back")
    
def submit():
    future = Executor().submit(slow_callable)
    future.add_done_callback(callback)
    return future
    
print(mutable)

# 1) Executor is locally scoped variable
# executor = Executor()
# future = executor.submit(slow_callable)

# 2) Executor is never assigned to a variable
# future = Executor().submit(slow_callable)

# 3) Executor is in a different scope
# future = submit()

future.add_done_callback(callback)

print(mutable)
future.result()
print(mutable)
```

The desired output is 

```
[]
[]
['Called back']
```

Where the waiting happens when we invoke `future.result()`. However, this is only the case for option (1) where the executor is assigned its own variable in same scope as the future object. Options (2) and (3) both give

```
[]
['Called back']
['Called back']
```

Where the waiting happens at the submit call.

This led me in the direction of garbage collection, which led me to:

https://github.com/pyiron/pympipool/blob/a81412d18aa3abc47829f384e1aa99c062f031ec/pympipool/shared/executorbase.py#L63-L67

(EDIT: Trying to get the preview blob to format nicely)

Changing the `wait=True` to `wait=False` resolves this issue and keeps the tests on my machine passing, but I don't know if it has other side effects.

### PR DESCRIPTION
**Pull request by liamhuber**
Closes #213.

I think the demo from that issue should be added as a unit test, but it was unclear to me where it should be added.

### CODE REVIEW

**Comment by liamhuber** [comment]
Unfortunately this still doesn't let me plug `pympipool.Executor` in place of the `CloudpickleProcessPoolExecutor` over in `pyiron_workflow`, but at least it gets the `Foo` example over in #213 running and gets _some_ tests passing in `pyiron_workflow`.

**Comment by liamhuber** [comment]
> Unfortunately this still doesn't let me plug `pympipool.Executor` in place of the `CloudpickleProcessPoolExecutor` over in `pyiron_workflow`, but at least it gets the `Foo` example over in #213 running and gets _some_ tests passing in `pyiron_workflow`.

Ok, failures were reasonable problems on the `pyiron_workflow` end and are resolved. A couple of tests hang indefinitely, but this might be harder to track down. Also I'm using a mac and #191, so maybe there is some connection there. Will try more later.

**Comment by liamhuber** [comment]
I guess the hanging might be related to #94 again since here I stopped waiting on deletion?

**Comment by liamhuber** [comment]
Note to self for tomorrow: locally, the hanging is actually throwing this error in pycharm even though the test run doesn't stop:

```
Traceback (most recent call last):
  File "/Users/huber/work/pyiron/pympipool/pympipool/backend/serial.py", line 64, in <module>
    main(argument_lst=sys.argv)
  File "/Users/huber/work/pyiron/pympipool/pympipool/backend/serial.py", line 30, in main
    input_dict = interface_receive(socket=socket)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huber/work/pyiron/pympipool/pympipool/shared/communication.py", line 147, in interface_receive
    return cloudpickle.loads(socket.recv())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tests.unit'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[24370,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by liamhuber** [comment]
Also the test that hangs has no problem running in a notebook

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
> Note to self for tomorrow: locally, the hanging is actually throwing this error in pycharm even though the test run doesn't stop:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/huber/work/pyiron/pympipool/pympipool/backend/serial.py", line 64, in <module>
>     main(argument_lst=sys.argv)
>   File "/Users/huber/work/pyiron/pympipool/pympipool/backend/serial.py", line 30, in main
>     input_dict = interface_receive(socket=socket)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/huber/work/pyiron/pympipool/pympipool/shared/communication.py", line 147, in interface_receive
>     return cloudpickle.loads(socket.recv())
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ModuleNotFoundError: No module named 'tests.unit'
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpiexec detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[24370,1],0]
>   Exit code:    1
> --------------------------------------------------------------------------
> ```

The error `ModuleNotFoundError: No module named 'tests.unit'` indicates that you executed the tests from the root of the repository. In the continuous integration environment we first enter the `tests` directory and then execute the tests in there. https://github.com/pyiron/pympipool/pull/162 An alternative option would be to add the tests directory to your `PYTHONPATH`. I am not exactly sure what `unittest` does in the background or how the other test frameworks work but I guess this should help to fix your issue locally.

**Comment by liamhuber** [comment]
> Looks good to me

Super. I added the examples from #213 as tests. I've put them in `test_future` because for me this is about the executor allowing the futures objects it creates to exist independently of itself, but I'm very open to relocating them if you think there's somewhere better.

**Comment by liamhuber** [comment]
> The error `ModuleNotFoundError: No module named 'tests.unit'` indicates that you executed the tests from the root of the repository. In the continuous integration environment we first enter the tests directory and then execute the tests in there. #162 An alternative option would be to add the tests directory to your `PYTHONPATH`. I am not exactly sure what unittest does in the background or how the other test frameworks work but I guess this should help to fix your issue locally.

Awesome, thank you for the hint! Indeed, when I manually add `.../pyiron_workflow/tests/unit` to my path, navigate there, and execute the individual tests from the command line it works fine. So, problem solved and `pympipool` is not plugging into `pyiron_workflow`!

Still, this solution is a little unsatisfying and I worry it might lead to user headaches if there are edge cases where they need to run around and modify their system env variables. Somehow the much simpler `pyiron_workflow.executors.CloudpickleProcessPoolExecutor` avoids this pitfall and works fine from the pycharm test suite.

Since the libraries are compatible in principle, I'm content to leave it here for now -- but I might open this as a separate issue when I try to actually add the next version of `pympipool` as a dependency of `pyiron_workflow`.

**Comment by jan-janssen** [comment]
> @jan-janssen what are you doing for the mac jobs, just re-running until they manage to pass?

Yes, it is super annoying

**Comment by jan-janssen** [comment]
@liamhuber Is it ok to merge this? I would like to release a new version with the updated documentation.

**Comment by liamhuber** [comment]
> @liamhuber Is it ok to merge this? I would like to release a new version with the updated documentation.

For sure. Can we get #187 in too? It's just extra test files, but that would make the next version really clearly support pyiron_workflow

**Pull request merged**
